#!/bin/sh
################################################################################
# Copyright (c) 2020 ModalAI, Inc. All rights reserved.
#
# author: james@modalai.com
################################################################################

set -e


echo ""
echo "Done installing voxl-mapper"
echo ""

# make sure there is a newline at the end here or opkg will whine
